# Generated by Django 4.1.2 on 2022-10-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_number', models.CharField(max_length=10)),
                ('V_type', models.CharField(choices=[('2', 'Two Wheeler'), ('3', 'Three Wheeler'), ('4', 'Four Wheeler')], max_length=1)),
                ('V_model', models.CharField(max_length=20)),
                ('V_description', models.TextField()),
            ],
        ),
    ]
