# Generated by Django 4.1.2 on 2022-10-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='V_description',
            new_name='Vehicle_description',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='V_model',
            new_name='Vehicle_model',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='V_number',
            new_name='Vehicle_number',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='V_type',
            new_name='Vehicle_type',
        ),
    ]
